In [1]:
import pandas as pd
import requests
import json

r = requests.get("https://data.cityofnewyork.us/resource/76xm-jjuj?$where=incident_datetime between '2005-01-10T00:00:00' and '2005-01-11T00:00:00'&$limit=50000")

df = pd.DataFrame(json.loads(r.text))
df.to_csv("test.csv", index=False)

In [2]:
df = pd.read_csv('test.csv')
df = df.fillna("")

In [3]:
timestamp_columns = [
          'incident_datetime', 'first_assignment_datetime', 'first_activation_datetime', 
          'first_on_scene_datetime', 'first_to_hosp_datetime', 'first_hosp_arrival_datetime', 
          'incident_close_datetime'
          ]
df[timestamp_columns] = df[timestamp_columns].apply(lambda col: pd.to_datetime(col, errors='coerce').astype(str).replace("NaT", ""))
bool_columns = [
    'valid_dispatch_rspns_time_indc', 'valid_incident_rspns_time_indc', 'held_indicator', 
    'reopen_indicator', 'special_event_indicator', 'standby_indicator', 'transfer_indicator'
    ]
pd.set_option('future.no_silent_downcasting', True)
df[bool_columns] = df[bool_columns].replace({'Y': True, 'N': False})

df

,cad_incident_id,incident_datetime,initial_call_type,initial_severity_level_code,final_call_type,final_severity_level_code,valid_dispatch_rspns_time_indc,dispatch_response_seconds_qy,valid_incident_rspns_time_indc,incident_close_datetime,...,special_event_indicator,standby_indicator,transfer_indicator,first_assignment_datetime,first_activation_datetime,first_on_scene_datetime,incident_response_seconds_qy,incident_travel_tm_seconds_qy,first_to_hosp_datetime,first_hosp_arrival_datetime
0,50100001,2005-01-10 00:00:12,OTHER,6,OTHER,6,False,0,False,2005-01-10 00:00:12,...,False,False,False,,,,,,,
1,50100002,2005-01-10 00:00:23,OTHER,6,OTHER,6,False,0,False,2005-01-10 00:00:23,...,False,False,False,,,,,,,
2,50100003,2005-01-10 00:00:36,OTHER,6,OTHER,6,False,0,False,2005-01-10 00:00:36,...,False,False,False,,,,,,,
3,50100004,2005-01-10 00:00:41,OTHER,6,OTHER,6,False,0,False,2005-01-10 00:00:41,...,False,False,False,,,,,,,
4,50100005,2005-01-10 00:00:59,DIFFBR,2,DIFFBR,2,True,65,True,2005-01-10 00:40:28,...,False,False,False,2005-01-10 00:02:04,2005-01-10 00:02:45,2005-01-10 00:10:38,579.0,514.0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3254,50103531,2005-01-10 23:57:58,DRUG,4,DRUG,4,True,140,True,2005-01-11 00:41:23,...,False,False,False,2005-01-11 00:00:18,2005-01-11 00:00:41,2005-01-11 00:08:03,605.0,465.0,2005-01-11 00:13:05,2005-01-11 00:21:18
3255,50103532,2005-01-10 23:58:31,SICK,6,SICK,6,True,733,True,2005-01-11 00:11:13,...,False,False,False,2005-01-11 00:10:44,,2005-01-11 00:11:07,756.0,23.0,,
3256,50103534,2005-01-10 23:59:15,INJURY,5,INJURY,5,True,420,True,2005-01-11 00:10:36,...,False,False,False,2005-01-11 00:06:15,2005-01-11 00:06:40,2005-01-11 00:08:31,556.0,136.0,,
3257,50103533,2005-01-10 23:59:18,SICPED,4,SICPED,4,True,66,True,2005-01-11 00:59:57,...,False,False,False,2005-01-11 00:00:24,2005-01-11 00:00:37,2005-01-11 00:10:12,654.0,588.0,2005-01-11 00:28:30,2005-01-11 00:41:25
3258,50103535,2005-01-10 23:59:58,CARD,3,CARD,3,True,49,True,2005-01-11 01:23:01,...,False,False,False,2005-01-11 00:00:47,2005-01-11 00:00:47,2005-01-11 00:08:01,483.0,434.0,2005-01-11 00:48:36,2005-01-11 00:50:05

In [5]:
df.columns

Index(['cad_incident_id', 'incident_datetime', 'initial_call_type',
       'initial_severity_level_code', 'final_call_type',
       'final_severity_level_code', 'valid_dispatch_rspns_time_indc',
       'dispatch_response_seconds_qy', 'valid_incident_rspns_time_indc',
       'incident_close_datetime', 'held_indicator',
       'incident_disposition_code', 'borough', 'incident_dispatch_area',
       'zipcode', 'policeprecinct', 'citycouncildistrict', 'communitydistrict',
       'communityschooldistrict', 'congressionaldistrict', 'reopen_indicator',
       'special_event_indicator', 'standby_indicator', 'transfer_indicator',
       'first_assignment_datetime', 'first_activation_datetime',
       'first_on_scene_datetime', 'incident_response_seconds_qy',
       'incident_travel_tm_seconds_qy', 'first_to_hosp_datetime',
       'first_hosp_arrival_datetime'],
      dtype='object')